runtime: python39

handlers:

  - url: /auth
    static_files: auth.html
    upload: auth.html

  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

