runtime: python39

handlers:

  - env_variables:
    DATABASE_URL: "mysql://root:Tanyaarda@34.72.212.141:3306/notesapp"
    JWT_SECRET: "rahasia"

  - url: /auth
    static_files: auth.html
    upload: auth.html

  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

